# Generated by Django 3.1 on 2020-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tamano_empresa', models.CharField(choices=[('Micro Empresa / Independiente', 'Micro Empresa / Independiente'), ('Pequeña Empresa', 'Pequeña Empresa'), ('Mediana Empresa', 'Mediana Empresa'), ('Gran Empresa', 'Gran Empresa')], max_length=30)),
                ('pais', models.CharField(choices=[('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Peru', 'Peru'), ('Colombia', 'Colombia'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil')], default='Chile', max_length=15)),
                ('edad', models.CharField(choices=[('Menor o igual de 20', 'Menor o igual de 20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('mas de 50', 'mas de 50')], max_length=25)),
                ('estudios', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Bootcamp', 'Bootcamp'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Máster', 'Master'), ('Doctorado', 'Doctorado')], max_length=15)),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('ingles', models.CharField(choices=[('Indiferente', 'Indiferente'), ('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Alto', 'Alto')], max_length=15)),
            ],
        ),
    ]
