# Generated by Django 3.1 on 2020-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0002_persona_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contrato',
            field=models.CharField(choices=[('Contrato Indefinido', 'Contrato Indefinido'), ('Contrato Plazo Fijo', 'Contrato Plazo Fijo'), ('Sin Trabajo', 'Sin Trabajo'), ('Boletas', 'Boletas')], default='Contrato Indefinido', max_length=30),
        ),
    ]
