# Generated by Django 3.1 on 2020-08-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0004_persona_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='experiencia',
            field=models.CharField(choices=[('menos de 1', 'menos de 1'), ('un año', 'un año'), ('dos años', 'dos años'), ('tres años', 'tres años'), ('cuatro años', 'cuatro años'), ('cinco años', 'cinco años'), ('seis años', 'seis años'), ('siete años', 'siete años'), ('ocho años', 'ocho años'), ('nueve años', 'nueve años'), ('mas de diez años', 'mas de diez años')], default='un año', max_length=50),
        ),
    ]
