# Generated by Django 3.1 on 2020-08-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0005_persona_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rentaLiquida',
            field=models.IntegerField(default=0),
        ),
    ]
