# Generated by Django 3.1 on 2020-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0006_persona_rentaliquida'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rentaBono',
            field=models.CharField(choices=[('0', '0'), ('0,5', '0,5'), ('1', '1'), ('1,5', '1,5'), ('2', '2'), ('2,5', '2,5'), ('3 o mas', '3 o mas')], default='0', max_length=50),
        ),
    ]
