# Generated by Django 3.1 on 2020-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0007_persona_rentabono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='duracionTrabajo',
            field=models.CharField(choices=[('Menos de 6 meses', 'Menos de 6 meses'), ('6 meses a 12 meses', '6 meses a 12 meses'), ('1 año a 2 años', '1 año a 2 años'), ('mas de 2 años', 'mas de 2 años')], default='6 meses a 12 meses', max_length=50),
        ),
    ]
