# Generated by Django 3.1 on 2020-08-13 20:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0009_persona_beneficiosempleador'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='FactoresCambioEmpleo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Beneficios no monetarios', 'Beneficios no monetarios'), ('Aprendizaje', 'Aprendizaje'), ('Desarrollo de Carrera', 'Desarrollo de Carrera'), ('Ahorro', 'Ahorro'), ('Reconocimiento', 'Reconocimiento'), ('Flexibilidad Horaria', 'Flexibilidad Horaria'), ('Bono de Gestión', 'Bono de Gestión'), ('Trabajo Remoto', 'Trabajo Remoto'), ('Clima Laboral', 'Clima Laboral'), ('Lejania de mi hogar', 'Lejania de mi hogar'), ('Sueldo', 'Sueldo'), ('Capacitación', 'Capacitación')], default=0, max_length=186),
        ),
    ]
