# Generated by Django 3.1 on 2020-08-14 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0010_persona_factorescambioempleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
