# Generated by Django 3.1 on 2020-08-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0011_persona_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha',
        ),
    ]
