# Generated by Django 3.1 on 2020-09-22 01:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0016_auto_20200914_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='BeneficiosEmpleador',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Alimentación', 'Alimentación'), ('Movilización', 'Movilización'), ('Plan de Salud', 'Plan de Salud'), ('Previsión / AFP', 'Previsión / AFP'), ('Celular / Computador', 'Celular / Computador'), ('Auto', 'Auto'), ('% Trading Profit Anual', '% Trading Profit Anual'), ('Gimnasio', 'Gimnasio'), ('Stock Options', 'Stock Options'), ('Equity', 'Equity'), ('Horario Flexible', 'Horario Flexible'), ('Trabajo Remoto', 'Trabajo Remoto'), ('Beneficios Flexibles', 'Beneficios Flexibles'), ('Capacitaciones', 'Capacitaciones')], default=0, max_length=202),
        ),
        migrations.AlterField(
            model_name='persona',
            name='FactoresCambioEmpleo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Beneficios no monetarios', 'Beneficios no monetarios'), ('Aprendizaje', 'Aprendizaje'), ('Desarrollo de Carrera', 'Desarrollo de Carrera'), ('Ahorro', 'Ahorro'), ('Reconocimiento', 'Reconocimiento'), ('Flexibilidad Horaria', 'Flexibilidad Horaria'), ('Bono de Gestión', 'Bono de Gestión'), ('Trabajo Remoto', 'Trabajo Remoto'), ('Clima Laboral', 'Clima Laboral'), ('Lejania de mi hogar', 'Lejania de mi hogar'), ('Sueldo', 'Sueldo'), ('Capacitación', 'Capacitación')], default=0, max_length=186),
        ),
    ]
