# Generated by Django 3.1 on 2020-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0020_auto_20201005_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rentaBono',
            field=models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3 o mas')], default=0),
        ),
    ]
