# Generated by Django 3.1 on 2020-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0021_auto_20201005_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
