# Generated by Django 3.1 on 2020-10-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0022_auto_20201007_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
