# Generated by Django 3.1 on 2020-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0025_auto_20201007_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
    ]
