# Generated by Django 3.1 on 2020-10-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0028_auto_20201021_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='ingles',
            new_name='ingles_hablado',
        ),
    ]
