# Generated by Django 3.1 on 2020-10-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0029_auto_20201021_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='actividad',
            field=models.CharField(choices=[('Empresa Fabril / Industrial', 'Empresa Fabril / Industrial'), ('Empresa Comercial', 'Empresa Comercial'), ('Empresa de Servicios', 'Empresa de Servicios'), ('Empresa Financiera', 'Empresa Financiera'), ('Gobierno', 'Gobierno'), ('Tecnologías de la información y la comunicación', 'Tecnologías de la información y la comunicación'), ('Otros(educación, salud, etc)', 'Otros(educación, salud, etc)')], default='Empresa Comercial', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.CharField(choices=[('Menor o igual de 20', 'Menor o igual de 20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41-45', '41-45'), ('46-50', '46-50'), ('más de 50', 'más de 50')], default='26-30', max_length=25),
        ),
    ]
