# Generated by Django 3.1 on 2020-10-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0031_auto_20201021_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tamano_empresa',
            field=models.CharField(choices=[('Micro Empresa / Independiente', 'Micro Empresa / Independiente'), ('Pequeña Empresa', 'Pequeña Empresa'), ('Mediana Empresa', 'Mediana Empresa'), ('Gran Empresa', 'Gran Empresa')], default='Micro Empresa / Independiente', max_length=30),
        ),
    ]
