# Generated by Django 3.1 on 2020-11-03 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0032_auto_20201021_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
