# Generated by Django 3.1 on 2020-11-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0033_auto_20201103_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
    ]
