# Generated by Django 3.1 on 2020-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0034_auto_20201103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Seleccionar', 'Seleccionar')], default='Seleccionar', max_length=11),
        ),
    ]
