# Generated by Django 3.1 on 2020-11-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioPersona', '0037_auto_20201111_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='actividad',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Empresa Fabril / Industrial', 'Empresa Fabril / Industrial'), ('Empresa Comercial', 'Empresa Comercial'), ('Empresa de Servicios', 'Empresa de Servicios'), ('Empresa Financiera', 'Empresa Financiera'), ('Gobierno', 'Gobierno'), ('Tecnologías de la información y la comunicación', 'Tecnologías de la información y la comunicación'), ('Otros(educación, salud, etc)', 'Otros(educación, salud, etc)')], default='Seleccionar', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Management / CTO', 'Management / CTO'), ('Management / Head of Infraestructure', 'Management / Head of Infraestructure'), ('Management / CIO', 'Management / CIO'), ('Management / IT Manager', 'Management / IT Manager'), ('Management / PMO', 'Management / PMO'), ('Management / Subgerente TI', 'Management / Subgerente TI'), ('Management / Jefe Informática', 'Management / Jefe Informática'), ('Desarrollo / Gerente Desarrollo', 'Desarrollo / Gerente Desarrollo'), ('Desarrollo / Gerente Proyectos', 'Desarrollo / Gerente Proyectos'), ('Desarrollo / Lider Técnico', 'Desarrollo / Lider Técnico'), ('Desarrollo / Arquitecto Sotware', 'Desarrollo / Arquitecto Sotware'), ('Desarrollo / Arquitecto Empresarial', 'Desarrollo / Arquitecto Empresarial'), ('Desarrollo / Desarrollador Front End', 'Desarrollo / Desarrollador Front End'), ('Desarrollo / Desarrollador Back End', 'Desarrollo / Desarrollador Back End'), ('Desarrollo / Full Stack', 'Desarrollo / Full Stack'), ('Desarrollo / Desarrollador Mobile', 'Desarrollo / Desarrollador Mobile'), ('Desarrollo / Consultor QA', 'Desarrollo / Consultor QA'), ('Desarrollo / Diseñador UX/UI', 'Desarrollo / Diseñador UX/UI'), ('Desarrollo / Jefe de Proyectos', 'Desarrollo / Jefe de Proyectos'), ('Desarrollo / Scrum Master', 'Desarrollo / Scrum Master'), ('Desarrollo / Agile Coach', 'Desarrollo / Agile Coach'), ('Desarrollo / Product Owner', 'Desarrollo / Product Owner'), ('Desarrollo / Ingeniero Devops', 'Desarrollo / Ingeniero Devops'), ('Desarrollo / Consultor RPA', 'Desarrollo / Consultor RPA'), ('Data & Analytics / Arquitecto de Datos ', 'Data & Analytics / Arquitecto de Datos '), ('Data & Analytics / Ingniero de Datos ', 'Data & Analytics / Ingniero de Datos '), ('Data & Analytics / Manager BI ', 'Data & Analytics / Manager BI '), ('Data & Analytics / Consultor BI', 'Data & Analytics / Consultor BI'), ('Data & Analytics / Chief Data Officer ', 'Data & Analytics / Chief Data Officer '), ('Data & Analytics / Digital Analitics Manager ', 'Data & Analytics / Digital Analitics Manager '), ('Data & Analytics / Data Scientist ', 'Data & Analytics / Data Scientist '), ('SAP ERP / Project Manager SAP', 'SAP ERP / Project Manager SAP'), ('SAP ERP / Consultor ABAP ', 'SAP ERP / Consultor ABAP '), ('SAP ERP / Consultor FICO ', 'SAP ERP / Consultor FICO '), ('SAP ERP / Consultor MM', 'SAP ERP / Consultor MM'), ('SAP ERP / Consultor SD ', 'SAP ERP / Consultor SD '), ('SAP ERP / Consultor PIPO', 'SAP ERP / Consultor PIPO'), ('SAP ERP / Consultor HR ', 'SAP ERP / Consultor HR '), ('SAP ERP / Consultor SAP otro ', 'SAP ERP / Consultor SAP otro '), ('Ciberseguridad / CISO ', 'Ciberseguridad / CISO '), ('Ciberseguridad / Manager Ciberseguridad  ', 'Ciberseguridad / Manager Ciberseguridad  '), ('Ciberseguridad / Ethical Hacker  ', 'Ciberseguridad / Ethical Hacker  '), ('Ciberseguridad / Pentester ', 'Ciberseguridad / Pentester '), ('Ciberseguridad / Analista en Ciberseguridad  ', 'Ciberseguridad / Analista en Ciberseguridad  '), ('Ciberseguridad / Ingeniero en Ciberseguridad ', 'Ciberseguridad / Ingeniero en Ciberseguridad '), ('Ciberseguridad / Jefe Proyectos Ciberseguridad  ', 'Ciberseguridad / Jefe Proyectos Ciberseguridad  '), ('Ciberseguridad / Arquitecto Ciberseguridad ', 'Ciberseguridad / Arquitecto Ciberseguridad '), ('Infraestructura / Técnico en Monitoreo ', 'Infraestructura / Técnico en Monitoreo '), ('Infraestructura / Soporte Técnico ', 'Infraestructura / Soporte Técnico '), ('Infraestructura / Jefe de Infraestructura  ', 'Infraestructura / Jefe de Infraestructura  '), ('Infraestructura / Ingeniero de Redes ', 'Infraestructura / Ingeniero de Redes '), ('Infraestructura / Arquitecto de Redes', 'Infraestructura / Arquitecto de Redes'), ('Infraestructura / SysOps ', 'Infraestructura / SysOps '), ('Infraestructura / Administrador de sistemas ', 'Infraestructura / Administrador de sistemas ')], default='Seleccionar', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='contrato',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Contrato Indefinido', 'Contrato Indefinido'), ('Contrato Plazo Fijo', 'Contrato Plazo Fijo'), ('Sin Trabajo', 'Sin Trabajo'), ('Boletas', 'Boletas')], default='Seleccionar', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='duracionTrabajo',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('menos de 6 meses', 'menos de 6 meses'), ('6 meses a 12 meses', '6 meses a 12 meses'), ('1 año a 2 años', '1 año a 2 años'), ('más de 2 años', 'más de 2 años')], default='Seleccionar', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Menor o igual de 20', 'Menor o igual de 20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41-45', '41-45'), ('46-50', '46-50'), ('más de 50', 'más de 50')], default='Seleccionar', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estudios',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Ninguno', 'Ninguno'), ('Bootcamp', 'Bootcamp'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Máster', 'Máster'), ('Doctorado', 'Doctorado')], default='Seleccionar', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='experiencia',
            field=models.IntegerField(choices=[('Seleccionar', 'Seleccionar'), (0, 'entre uno a once meses'), (2, 'un año'), (2, 'dos años'), (3, 'tres años'), (4, 'cuatro años'), (5, 'cinco años'), (6, 'seis años'), (7, 'siete años'), (8, 'ocho años'), (9, 'nueve años'), (10, 'más de diez años')], default='Seleccionar'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ingles_escrito',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Indiferente', 'Indiferente'), ('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Alto', 'Alto')], default='Seleccionar', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ingles_hablado',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Indiferente', 'Indiferente'), ('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Alto', 'Alto')], default='Seleccionar', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Chile', 'Chile')], default='Seleccionar', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rentaBono',
            field=models.FloatField(choices=[('Seleccionar', 'Seleccionar'), (0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3 o mas')], default='Seleccionar'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tamano_empresa',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Micro Empresa / Independiente', 'Micro Empresa / Independiente'), ('Pequeña Empresa', 'Pequeña Empresa'), ('Mediana Empresa', 'Mediana Empresa'), ('Gran Empresa', 'Gran Empresa')], default='Seleccionar', max_length=30),
        ),
    ]
